layout_spectrum: 0.6927076
typography_spectrum: 0.9674186
color:
  saturation: 0.02447159
  lightness: 0.3619307
  brandStrength: 0.2200937
  rhythmicContrast: 0.7911228
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: 'Barbara&Martin'
