name: 'Barbara&Martin'
favicon: null
layout_spectrum: 0.6927076
typography_spectrum: 0.9674186
title: Loving Live
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2200937
  lightness: 0.3619307
  saturation: 0.02447159
  rhythmicContrast: 0.7911228
purpose: []
